name: Deploy using OIDC

on:
  push:
    branches: [ "main" ]

env:
  BUCKET_NAME: "my-oidc-github-bucket-july-demo"
  AWS_REGION: "ap-south-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.5.7  # 🔄 Use a modern version

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::938320847138:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      # - name: Terraform Init
      #   run: terraform init -reconfigure

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Upload index.html to S3
        run: aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/index.html

      - name: List S3 Bucket Contents
        run: aws s3 ls s3://${{ env.BUCKET_NAME }}/
